django-authenticate-v1.0.0/src/accounts/urls.py
from django.urls import path
from . import views

'''app_name = 'accounts'

urlpatterns = [
    path('<str:username>/profile/', views.verify_user, name='profile')
]'''

django-authenticate-v1.0.0/src/authenticate/urls.py
from django.urls import path
from .views import CustomLoginView, CustomLogoutView
from . import views

app_name = "authenticate"
urlpatterns = [
    path("home/", views.IndexView, name='home'),
    path("register/", views.RegisterView, name='register'),
    path("login/", CustomLoginView.as_view(), name='login'),
    path("<str:username>/dashboard/", views.DashboardView, name='dashboard'),
    path('logout/', CustomLogoutView.as_view(), name='logout'),
    path('verify_email/<str:token>/', views.verify_email, name='verify_email'),
    #path('logout/', LogoutView.as_view(), name='logout'),
]

django-authenticate-v1.0.0/src/accounts/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.contrib.auth.models import UserManager
# Create your models here.

RegModel = get_user_model()

class Profile(models.Model):

    user = models.OneToOneField(RegModel, on_delete=models.CASCADE, related_name='profile')
    is_verified = models.BooleanField(default=False)
    bio = models.TextField(blank=True, null=True)
    avatar = models.ImageField(upload_to='profile-pic/', blank=True, null=True)

    objects = UserManager()

    def __str__(self):
        return f"{self.user.username}'s Profile"

django-authenticate-v1.0.0/src/authenticate/models.py
from django.contrib.auth.models import AbstractUser, UserManager
#from django.contrib import admin
from django.db import models
from django.utils.translation import gettext_lazy as _
# Create your models here.
class Registrar(AbstractUser):

    email = models.EmailField(_("email address"), blank=True, unique=True)
    is_verified = models.BooleanField(
        _("Email Verified"),
        default=False,
        help_text=_("Designates whether the user has verified email address."),
    )

    is_active = models.BooleanField(
        _("active"),
        default=False,
        help_text=_(
            "Designates whether this user should be treated as active. "
            "Unselect this instead of deleting accounts."
        ),
    )

    objects = UserManager()
    REQUIRED_FIELDS = ["email", 'first_name', 'last_name']

#admin.site.register(Registrar)

django-authenticate-v1.0.0/src/authenticate/forms.py
from django.contrib.auth import get_user_model, authenticate
from django.core.exceptions import ValidationError
from django import forms
from django.contrib.auth.forms import AuthenticationForm

RegModel = get_user_model()

class RegistrationForm(forms.models.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput, label="Password")
    confirm_password = forms.CharField(widget=forms.PasswordInput, label="Confirm Password")
    class Meta():
        model = RegModel
        fields = ['email', 'username','password']

    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get('password')
        confirm_password = cleaned_data.get('confirm_password')
        email = cleaned_data.get('email')

        if password and confirm_password and password != confirm_password:
            raise forms.ValidationError("Passwords do not match.")

        '''if RegModel.objects.filter(email=email).exclude(pk=self.instance.pk).exists():
            raise forms.ValidationError("This email is already in use.")'''

        return cleaned_data

    #TODO: To beresolved in v.03
    '''def confirm_register_allowed(self, user):  

        if user.is_verified:        
            raise ValidationError(
                "Email is already Verified. Account with this email already Exists",
                code="verified",
            )'''

class LoginForm(AuthenticationForm):

    def clean(self):
        username = self.cleaned_data.get("username")
        password = self.cleaned_data.get("password")

        #Validating Authentications
        if username is not None and password:
            try:
                self.user = RegModel.objects.get(username=username)
            except RegModel.DoesNotExist:
                raise ValidationError("User is not Registered!!")

            self.user_cache = authenticate(
                self.request, username=username, password=password
            )
            #Controls whether the given user is active or not.
            if self.user_cache is None:
                if  not self.user.is_active:
                    self.confirm_login_allowed(self.user)
                else:
                    raise self.get_invalid_login_error()

        return self.cleaned_data

    def confirm_login_allowed(self, user):
        """
        Controls whether the given User may log in. This is a policy setting,
        independent of end-user authentication. This default behavior is to
        allow login by active users, and reject login by inactive users.

        If the given user cannot log in, this method should raise a
        ``ValidationError``.

        If the given user may log in, this method should return None.
        """
        if not user.is_active:
            raise ValidationError(
                self.error_messages["inactive"],
                code="inactive",
            )

django-authenticate-v1.0.0/src/authenticate/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.contrib import messages
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.views.decorators.csrf import csrf_protect, requires_csrf_token
from .forms import RegistrationForm, LoginForm
from django.contrib.auth.views import LoginView, LogoutView
from django.core.signing import TimestampSigner, BadSignature
from django.contrib.auth import get_user_model
from .email import VerificationEmail
from .signals import user_created_signal
# Create your views here.

RegModel = get_user_model()
signer = TimestampSigner()
send = VerificationEmail()


def verify_email(request, token):
    try:
        email = signer.unsign(token, max_age=84600)
    except BadSignature:
        return HttpResponse("Invalid or expired token.")

    try:
        user = RegModel.objects.get(email=email)
        if user.is_verified:
            messages.info(request, "Email is already verified. Login!")
            return HttpResponseRedirect(reverse('authenticate:login'))
        user.is_active = True
        user.is_verified = True
        user.save()
        user_created_signal.send_robust(sender=RegModel, instance=user)
        return HttpResponse("Email verified successfully.")
    except RegModel.DoesNotExist:
        return HttpResponse("User does not exist.")


def IndexView(request):
    return render(request, 'authenticate/home.html')

@login_required
def DashboardView(request, username):
    if request.user.username != username:
        # Prevent access to another user's dashboard
        return render(request, '403.html', status=403)

    return render(request, 'authenticate/dashboard.html', {'username': username})

@csrf_protect
@requires_csrf_token
def RegisterView(request):

    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.set_password(form.cleaned_data['password'])
            user.save()
            send.send_verification_email(user)
            messages.success(request, "You are successfully registered!!! Please check your email to verify your account.")
            return HttpResponseRedirect(reverse('authenticate:home'))
        else:
            messages.error(request, 'Registration failed. Please correct the errors below.')
            return render(request, 'authenticate/register.html', {'form': form})
    else:
        form = RegistrationForm()

    return render(request, 'authenticate/register.html', {'form':form})


class CustomLoginView(LoginView):
    form_class = LoginForm
    template_name = 'authenticate/login.html'
    #redirect_authenticated_user = True
    def get_success_url(self):
        # Redirect to a user-specific dashboard
        return reverse('authenticate:dashboard', kwargs={'username': self.request.user.username})


class CustomLogoutView(LogoutView):
    template_name = 'authenticate/logout.html'

django-authenticate-v1.0.0/src/authenticate/templates/authenticate/dashboard.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'authenticate/style.css' %}">
    <title>mydashboard</title>
</head>
<body>
            {% if messages %}
            <div>
            {% for message in messages %}
                <div class="alert alert-{{ message.tags }}" role="alert">
                    {{ message }}
                </div>
            {% endfor %}
            </div>
            {% endif %}

<h1>WELCOME TO YOUR DASHBOARD!!!</h1>
<form  action="{% url 'authenticate:logout' %}" method="post" style="display:inline">
    {% csrf_token %}
    <button type="submit">Logout</button>
</form>
</body>
</html>

django-authenticate-v1.0.0/src/authenticate/templates/authenticate/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'authenticate/style.css' %}">
    <title>Home</title>
</head>
<body>
    {% if messages %}
            <div>
            {% for message in messages %}
                <div class="alert alert-{{ message.tags }}" role="alert">
                    {{ message }}
                </div>
            {% endfor %}
            </div>
    {% endif %}
</body>
</html>

django-authenticate-v1.0.0/src/authenticate/templates/authenticate/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'authenticate/style.css' %}">
    <title>Home</title>
</head>
<body>
    {% if messages %}
            <div>
            {% for message in messages %}
                <div class="alert alert-{{ message.tags }}" role="alert">
                    {{ message }}
                </div>
            {% endfor %}
            </div>
    {% endif %}
</body>
</html>

django-authenticate-v1.0.0/src/authenticate/templates/authenticate/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login Page</title>
    <link rel="stylesheet" href="{% static 'authenticate/src/tailwind.css' %}">
    <link rel="stylesheet" href="{% static 'authenticate/style.css' %}">
</head>

<body class="bg-pattern h-screen flex flex-col justify-center items-center">
    <div class="bg-gray-900 bg-opacity-80 p-8 rounded-lg shadow-lg w-full max-w-sm text-center">
        <h2 class="text-2xl font-bold mb-4 text-[#007bff]">DeployCrafts</h2>
        <p class="text-lg font-semibold mb-4 text-orange-500">Login Credentials</p>
        <form action="{% url 'authenticate:login' %}" method="post">
            {% csrf_token %}
            <!-- Display form errors (if any) -->
            {% for field in form %}
                {% if field.errors %}
                    <p class="text-red-500 text-sm">{{ field.label }}: {{ field.errors|join:", " }}</p>
                {% endif %}
            {% endfor %}

            <!-- Display non-field errors -->
            {% if form.non_field_errors %}
                <div style="color: red;">
                    <ul>
                        {% for error in form.non_field_errors %}
                            <li>{{ error }}</li>
                        {% endfor %}
                    </ul>
                </div>
            {% endif %}

            <!-- Display messages error -->
            {% if messages %}
            <div>
            {% for message in messages %}
                <div class="alert alert-{{ message.tags }}" role="alert">
                    {{ message }}
                </div>
            {% endfor %}
            </div>
            {% endif %}


            <!-- Username/Email -->
            <div class="mb-4">
                <input type="text" name="username" placeholder="Username"
                       class="w-full p-2 border border-gray-300 rounded text-black" required autocomplete="off" autofocus="True">
            </div>

            <!-- Password -->
            <div class="mb-4">
                <input type="password" name="password" placeholder="Password"
                       class="w-full p-2 border border-gray-300 rounded text-black" required autocomplete="new-password">
            </div>

            <button type="submit" class="cta">Login</button>
        </form>
        <p class="mt-4 text-white">No account yet? <a href="{% url 'authenticate:register' %}" class="text-blue-500 hover:underline">Register HERE</a></p>
    </div>
<footer>
    <p>Powered by <strong>DeployCrafts</strong></p>
</footer>
</body>
</html>

django-authenticate-v1.0.0/src/authenticate/templates/authenticate/logout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Logged Out</title>
    <link rel="stylesheet" href="{% static 'authenticate/style.css' %}">
    <link rel="stylesheet" href="{% static 'authenticate/src/tailwind.css' %}">
</head>
<body>
    <h1>YOU HAVE SUCCESSFULLY LOGGEDOUT!!!</h1>
<p><a href="{% url 'authenticate:login' %}">Login Again</a></p>
</body>
</html>

django-authenticate-v1.0.0/src/authenticate/templates/authenticate/register.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Register Page</title>
    <link rel="stylesheet" href="{% static 'authenticate/src/tailwind.css' %}">
    <link rel="stylesheet" href="{% static 'authenticate/style.css' %}">
</head>

<body class="bg-pattern h-screen flex flex-col justify-center items-center">
    <div class="bg-gray-900 bg-opacity-80 p-8 rounded-lg shadow-lg w-full max-w-sm text-center">
        <h2 class="text-2xl font-bold mb-4 text-[#007bff]">DeployCrafts</h2>
        <p class="text-lg font-semibold mb-4 text-orange-500">Register</p>
        <form action="{% url 'authenticate:register' %}" method="post">
            {% csrf_token %}
            <!-- Display form errors (if any) -->
            {% for field in form %}
                <div>
                <!-- Display field-specific errors -->
                    {% if field.errors %}
                        <ul style="color: red;">
                            {% for error in field.errors %}
                                <li>{{ error }}</li>
                            {% endfor %}
                        </ul>
                    {% endif %}
                </div>
            {% endfor %}

            <!-- Display non-field errors -->
            {% if form.non_field_errors %}
                <div style="color: red;">
                    <ul>
                        {% for error in form.non_field_errors %}
                            <li>{{ error }}</li>
                        {% endfor %}
                    </ul>
                </div>
            {% endif %}

            <!-- Display messages error -->
            {% if messages %}
            <div>
            {% for message in messages %}
                <div class="alert alert-{{ message.tags }}" role="alert">
                    {{ message }}
                </div>
            {% endfor %}
            </div>
            {% endif %}
            <!-- Username -->
            <div class="mb-4">
                <input type="text" name="username" placeholder="Username"
                       class="w-full p-2 border border-gray-300 rounded text-black"
                       value="{{ form.username.value|default:'' }}" required>
            </div>

            <!-- Email -->
            <div class="mb-4">
                <input type="email" name="email" placeholder="Email Address"
                       class="w-full p-2 border border-gray-300 rounded text-black"
                       value="{{ form.email.value|default:'' }}" required>
            </div>

            <!-- Password -->
            <div class="mb-4">
                <input type="password" name="password" placeholder="Password"
                       class="w-full p-2 border border-gray-300 rounded text-black" required autocomplete="new-password">
            </div>

            <!-- Confirm Password -->
            <div class="mb-4">
                <input type="password" name="confirm_password" placeholder="Confirm Password"
                       class="w-full p-2 border border-gray-300 rounded text-black" required autocomplete="new-password">
            </div>

            <button type="submit" class="cta">Register</button>
        </form>
        <p class="mt-4 text-white">Already have an account? <a href="{% url 'authenticate:login' %}" class="text-blue-500 hover:underline">Login HERE</a></p>
    </div>
<footer>
    <p>Powered by <strong>DeployCrafts</strong></p>
</footer>
</body>
</html>